apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cicd-pipeline 
  region: ap-south-1 

nodeGroups:
  - name: ng-1 
    instanceType: t2.medium 
    desiredCapacity: 3 
    ssh:
      allow: false 
